name: Otomatik Film Botu

on:
  schedule:
    - cron: '0 0,12 * * *'
  workflow_dispatch:

# GITHUB BOTUNA YAZMA YETKİSİ VERİYORUZ
permissions:
  contents: write

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu İndir
        uses: actions/checkout@v3

      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Gerekli Modülleri Yükle
        run: pip install -r requirements.txt

      - name: Botu Çalıştır ve Filmleri Çek
        run: python bot.py

      - name: Yeni Verileri GitHub'a Kaydet
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add veritabani.json
          
          # Eğer dosyada değişiklik varsa kaydet, yoksa atla
          if ! git diff-index --quiet HEAD; then
            git commit -m "🤖 Otomatik Güncelleme: Yeni filmler eklendi"
            git push
          else
            echo "Kütüphane zaten güncel, değişiklik yapılmadı."
          fi
